### ISSUE TITLE
With chromium codeblock.js is not executed (on demo page)

### ISSUE THREAD

**Issue by gildas-lormeau** [Ink/codeblock.js#2]
With Chromium (29.0.1506.0), Codeblock demos won't work because `codeblock.js` is served with the wrong MIME type (i.e. `text/plain`) and the browser refuses to execute it. 
You could host your JS file on GitHub Pages (i.e. `github.io` domain) to fix this issue.

**Comment by evanc** [comment]
There's a service [rawgithub.com](rawgithub.com) you can use that fixes the MIME types- just replace `raw.github.com` with `rawgithub.com` .

**Comment by jschuur** [comment]
Ditto in regular Chrome v27.0.1453.81 Mac OS X.

**Comment by chapel** [comment]
The proper thing to do would be to host it on the github pages branch.

**Comment by brettcvz** [comment]
Closed, thanks @chapel!
